name: Create Player Website

on:
  repository_dispatch:
    types:
      - create_player_website

jobs:
  create-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create player directory
        run: |
          mkdir -p players/${{ github.event.client_payload.folderName }}

      - name: Copy template files
        run: |
          cp -r players/template1/* players/${{ github.event.client_payload.folderName }}/

      - name: Create config.js
        run: |
          cat > players/${{ github.event.client_payload.folderName }}/config.js << 'EOL'
          const config = ${{ toJson(github.event.client_payload) }};
          export default config;
          EOL

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add players/${{ github.event.client_payload.folderName }}
          git commit -m "Create new player website: ${{ github.event.client_payload.folderName }}"
          git push 