name: Duplicate Folder with Custom Name

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: "Enter the new folder name"
        required: true
        type: string

jobs:
  duplicate-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Duplicate Folder
        run: |
          cp -r existing-folder ${{ github.event.inputs.folder_name }}
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Duplicated folder as ${{ github.event.inputs.folder_name }}"
          git push
