name: CI Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use GitHub Token
        run: |
          echo "The GitHub token is: ${{ secrets.MY_GITHUB_TOKEN }}"
