name: Upload Teacher Website

on:
  workflow_dispatch:  # Allows manual trigger
  repository_dispatch:  # Allows JavaScript to trigger it
    types: [upload-teacher]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Prevents using default GitHub credentials

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Create new teacher folder
        run: |
          TEACHER_DIR="teacher/${{ github.event.client_payload.teacher_name }}"
          mkdir -p $TEACHER_DIR
          echo "${{ github.event.client_payload.index_html }}" | base64 --decode > $TEACHER_DIR/index.html
          echo "${{ github.event.client_payload.script_js }}" | base64 --decode > $TEACHER_DIR/script.js
          echo "${{ github.event.client_payload.styles_css }}" | base64 --decode > $TEACHER_DIR/styles.css
          touch $TEACHER_DIR/.updated  # Ensure Git detects changes

      - name: Ensure Git Detects Changes
        run: |
          echo "Updating timestamp: $(date)" >> .github/update.log
          git add .
          git status  # Debugging step to check if Git detects changes

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure GitHub Token is used
        run: |
          if git diff --staged --quiet; then
            echo "⚠️ No changes detected. Skipping commit and push."
          else
            git commit -m "Updated teacher site for ${{ github.event.client_payload.teacher_name }}"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          fi
