name: Upload Teacher Website

on:
  workflow_dispatch:  # Allows manual trigger
  repository_dispatch:  # Allows external trigger from JavaScript
    types: [upload-teacher]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Create new teacher folder
        run: |
          TEACHER_DIR="teacher/${{ github.event.client_payload.teacher_name }}"
          mkdir -p $TEACHER_DIR
          echo "${{ github.event.client_payload.index_html }}" | base64 --decode > $TEACHER_DIR/index.html
          echo "${{ github.event.client_payload.script_js }}" | base64 --decode > $TEACHER_DIR/script.js
          echo "${{ github.event.client_payload.styles_css }}" | base64 --decode > $TEACHER_DIR/styles.css

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Token stored securely in GitHub Secrets
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add teacher/${{ github.event.client_payload.teacher_name }}
          git commit -m "Added teacher site for ${{ github.event.client_payload.teacher_name }}"
          git push origin main
